FROM node:22-alpine

RUN mkdir -p /home/node/app/node_modules

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

# Expose the port for web server
EXPOSE 8080

CMD [ "node", "app.js" ]