FROM node:22-alpine

RUN mkdir -p /home/node/app/node_modules

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

# Set the environment variable
ENV NODE_ENV=production

# Expose the port for web server
EXPOSE 8080

# No need to expose the port for api server

CMD [ "node", "app.js" ]