name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the web Docker image
      run: docker build . --file dockerfile.web.prod --tag acegi123/conestoga-provincial-park-web:prod
    - name: Push the web Docker image
      run: docker push acegi123/conestoga-provincial-park-web:prod
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: 'actions/checkout@v4'
    - name: Log in to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Deploy the web Docker image to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        image: 'conestoga-provincial-park-web:prod'
        service: 'conestogapark-web'
